# Generated by Django 4.0.1 on 2022-01-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_image_link_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
